### PR TITLE
This reapplies fixes from #44 for stackscript data

### PR DESCRIPTION
**Pull request by akerl**

### CODE REVIEW

**Comment by akerl** [comment]
Without this, HEAD panics when setting stackscript data:

```
panic: assignment to entry in nil map
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: 
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: goroutine 71 [running]:
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: github.com/terraform-providers/terraform-provider-linode/linode.createInstanceDisk(0xc000090c00, 0xc00003e240, 0x3c, 0xc000268810, 0x0, 0xbb8, 0xc00026a440, 0x0, 0xc00026a580, 0xc00026a5c0, ...)
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /home/akerl/src/armorfret/terraform-provider-linode/linode/linode_instance_helpers.go:511 +0x62e
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: github.com/terraform-providers/terraform-provider-linode/linode.resourceLinodeInstanceCreate(0xc0001d4070, 0x10bbd20, 0xc0000c2680, 0x2, 0x1a95080)
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /home/akerl/src/armorfret/terraform-provider-linode/linode/resource_linode_instance.go:1022 +0x21f0
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000115b00, 0xc0002408c0, 0xc000628e00, 0x10bbd20, 0xc0000c2680, 0xc000132e01, 0xc0003b4c00, 0xc000132ed0)
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /home/akerl/.go/pkg/mod/github.com/hashicorp/terraform@v0.12.0/helper/schema/resource.go:286 +0x365
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc000406200, 0xc0005b1908, 0xc0002408c0, 0xc000628e00, 0xc00037ae08, 0xc000010fe8, 0xf43c40)
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /home/akerl/.go/pkg/mod/github.com/hashicorp/terraform@v0.12.0/helper/schema/provider.go:285 +0x99
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000bea30, 0x131daa0, 0xc0005d0f90, 0xc0001444e0, 0xc0000bea30, 0xc0005d0f90, 0xc000291a80)
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /home/akerl/.go/pkg/mod/github.com/hashicorp/terraform@v0.12.0/helper/plugin/grpc_provider.go:842 +0x892
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1082a40, 0xc0000bea30, 0x131daa0, 0xc0005d0f90, 0xc0002405f0, 0x0, 0x131daa0, 0xc0005d0f90, 0xc000250800, 0x7a8)
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /home/akerl/.go/pkg/mod/github.com/hashicorp/terraform@v0.12.0/internal/tfplugin5/tfplugin5.pb.go:3019 +0x217
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004fe780, 0x1329b00, 0xc0004ff680, 0xc000274100, 0xc000321530, 0x1a69240, 0x0, 0x0, 0x0)
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /home/akerl/.go/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:966 +0x46a
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: google.golang.org/grpc.(*Server).handleStream(0xc0004fe780, 0x1329b00, 0xc0004ff680, 0xc000274100, 0x0)
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /home/akerl/.go/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:1245 +0xd16
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000361f0, 0xc0004fe780, 0x1329b00, 0xc0004ff680, 0xc000274100)
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /home/akerl/.go/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:685 +0xbb
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2019-11-02T05:45:09.065Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /home/akerl/.go/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:683 +0xa1
2019-11-02T05:45:09.069Z [DEBUG] plugin: plugin process exited: path=/home/akerl/src/akerl/linode-account/.terraform/plugins/linux_amd64/terraform-provider-linode_v1.8.0_x4 pid=86843 error="exit status 2"
2019/11/02 05:45:09 [DEBUG] module.red-vpn.linode_instance.vpn: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2019/11/02 05:45:09 [TRACE] module.red-vpn: eval: *terraform.EvalMaybeTainted
```

**Comment by phillc** [comment]
I have confirmed this bug, and have confirmed that this fix fixes the issue. I want to dig a little further to poke at a couple test cases. Hope to have it merged by the end of the week.

**Comment by phillc** [comment]
@akerl Thank you! I'll try to get a release cut next week.

**Comment by phillc** [comment]
included in 1.9.0

**Pull request merged**
