### PR TITLE
initialize disk opts stackscript data

### PR DESCRIPTION
**Pull request by akerl**
This should fix https://gist.github.com/akerl/55d9778d423aa0c385e8527ea2301b7f

### CODE REVIEW

**Comment by yuriy-yarosh** [comment]
Specifying any stackscript data opts as of now is broken..
`diskOpts.StackscriptData` are not being allocated at all.
Please merge this ASAP.

**Comment by akerl** [comment]
@ellisbenjamin It looks like this was reverted? I’m not sure why... the original error is now recurring when trying to set stackscript parameters

**Comment by akerl** [comment]
Showing the current trace back:

```
Error: rpc error: code = Unavailable desc = transport is closing


panic: assignment to entry in nil map
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: 
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: goroutine 85 [running]:
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: github.com/terraform-providers/terraform-provider-linode/linode.createInstanceDisk(0xc0004e3800, 0xc00003c200, 0x3c, 0xc000113830, 0x0, 0xbb8, 0xc000251380, 0xc0002514c0, 0xc0002515c0, 0xc0002516c0, ...)
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-linode/linode/linode_instance_helpers.go:511 +0x62e
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: github.com/terraform-providers/terraform-provider-linode/linode.resourceLinodeInstanceCreate(0xc0002b1c70, 0x10b2540, 0xc000436480, 0x2, 0x1c69b80)
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-linode/linode/resource_linode_instance.go:1022 +0x23eb
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: github.com/terraform-providers/terraform-provider-linode/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc00014d980, 0xc0000143c0, 0xc000282f00, 0x10b2540, 0xc000436480, 0xc000588401, 0xc000584c88, 0xf46400)
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-linode/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:286 +0x3b4
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: github.com/terraform-providers/terraform-provider-linode/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc000428080, 0xc0000aba58, 0xc0000143c0, 0xc000282f00, 0xc0004b15e8, 0xc00013c578, 0xf48320)
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-linode/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:285 +0x18f
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: github.com/terraform-providers/terraform-provider-linode/vendor/github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000146500, 0x1331a00, 0xc000558600, 0xc000140600, 0xc000146500, 0xc000558600, 0xc000225bd0)
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-linode/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:842 +0x894
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: github.com/terraform-providers/terraform-provider-linode/vendor/github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x107a840, 0xc000146500, 0x1331a00, 0xc000558600, 0xc0000141e0, 0x0, 0x1331a00, 0xc000558600, 0xc0004c1800, 0x7a8)
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-linode/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3019 +0x23e
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: github.com/terraform-providers/terraform-provider-linode/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001800, 0x133cda0, 0xc0004e2f00, 0xc000538000, 0xc000342ed0, 0x1c3e820, 0x0, 0x0, 0x0)
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-linode/vendor/google.golang.org/grpc/server.go:966 +0x470
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: github.com/terraform-providers/terraform-provider-linode/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000001800, 0x133cda0, 0xc0004e2f00, 0xc000538000, 0x0)
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-linode/vendor/google.golang.org/grpc/server.go:1245 +0xd25
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: github.com/terraform-providers/terraform-provider-linode/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00014a170, 0xc000001800, 0x133cda0, 0xc0004e2f00, 0xc000538000)
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-linode/vendor/google.golang.org/grpc/server.go:685 +0x9f
2019-11-02T05:30:57.680Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4: created by github.com/terraform-providers/terraform-provider-linode/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2019-11-02T05:30:57.685Z [DEBUG] plugin.terraform-provider-linode_v1.8.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-linode/vendor/google.golang.org/grpc/server.go:683 +0xa1
2019-11-02T05:30:57.690Z [DEBUG] plugin: plugin process exited: path=/home/akerl/src/akerl/linode-account/.terraform/plugins/linux_amd64/terraform-provider-linode_v1.8.0_x4 pid=82533 error="exit status 2"
2019/11/02 05:30:57 [DEBUG] module.orange-vpn.linode_instance.vpn: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2019/11/02 05:30:57 [TRACE] module.orange-vpn: eval: *terraform.EvalWriteState
```

**Comment by akerl** [comment]
Huh. It looks like this is doubly broken: 1.8.0 is from way back in July, so it never included the fix, *and* the fix was reverted after being applied

**Pull request merged**
